parser: babel-eslint
extends: airbnb
env:
  browser: true
  jest: true
rules:
  semi:
    - error
    - never
  react/no-danger: error
  react/no-comment-textnodes: off
  jsx-a11y/img-has-alt: off
  react/no-direct-mutation-state: error
  react/no-string-refs: error
  react/jsx-handler-names: error
  react/jsx-boolean-value:
    - error
    - never
  react/sort-comp: warn
  react/jsx-no-bind:
    - error
    - ignoreRefs: true
      allowArrowFunctions: false
      allowBind: false
  react/jsx-no-duplicate-props: error
  react/jsx-key:
    - error
  react/sort-prop-types:
    - error
    - ignoreCase: true
      callbacksLast: true
      requiredFirst: true
  react/jsx-sort-props:
    - warn
    - callbacksLast: true
      shorthandFirst: true
      ignoreCase: true
  react/react-in-jsx-scope: off
  react/jsx-filename-extension: off
  import/no-extraneous-dependencies: off
  global-require: off
  no-underscore-dangle: off
  import/imports-first: off
  jsx-a11y/no-static-element-interactions: off
  jsx-a11y/anchor-has-content: off
  import/extensions: off
  comma-dangle:
   - error
   - arrays: always-multiline
     objects: always-multiline
     imports: always-multiline
     exports: always-multiline
     functions: never
