parser: babel-eslint
extends: airbnb
env:
  browser: true
rules:
  semi:
    - error
    - never
  react/no-danger: error
  react/no-comment-textnodes: error
  react/no-direct-mutation-state: error
  react/no-string-refs: error
  react/jsx-handler-names: error
  react/jsx-boolean-value:
    - error
    - never
  react/sort-comp: error
  react/jsx-no-bind:
    - error
    - ignoreRefs: true
      allowArrowFunctions: false
      allowBind: false
  react/jsx-no-duplicate-props: error
  react/jsx-key:
    - error
  react/sort-prop-types:
    - error
    - ignoreCase: true
      callbacksLast: true
      requiredFirst: true
  react/jsx-sort-props:
    - error
    - callbacksLast: true
      shorthandFirst: true
      ignoreCase: true
  react/react-in-jsx-scope: off
  react/jsx-uses-react: off
  react/jsx-filename-extension: off
  import/no-extraneous-dependencies: off
  global-require: off
